### ISSUE TITLE
Mkhomedir issue on CentOS 8

### ISSUE THREAD

**Issue by ybrock** [sgnl05/sgnl05-sssd#104]
Hi,

I've found an issue with CentOS 8.
At line 299 of init.pp, you have to use another fact than $::facts['os']['name'] == 'Redhat'  to make it work on CentOS 8 :

>     case $::osfamily {                                                                                     
      'RedHat': {                                                                                          
        if ($::facts['os']['name'] == 'Fedora' and versioncmp($::facts['os']['release']['major'], '28') >= 0) or
        ( $::facts['os']['name'] == 'Redhat' and versioncmp($::facts['os']['release']['major'], '8') >= 0) {

Something like :
        ( $::facts['os']['family'] == 'Redhat' and versioncmp($::facts['os']['release']['major'], '8') >= 0) {

What do you think ? Should I submit a pull request, or somebody wants to fix it ?

Cheers
Yvan

**Comment by ghoneycutt** [comment]
Hi @ybrock Could you please submit a pull request.

**Comment by ybrock** [comment]
My pull request was merge. We can close the issue.
Thanks for the merge
