### ISSUE TITLE
please update puppetlabs/stdlib dependency to < 7.0.0

### ISSUE THREAD

**Issue by kmarcroft** [sgnl05/sgnl05-sssd#109]
Hi,

please update the dependency for above from:
`"dependencies": [
    {"name":"puppetlabs/stdlib","version_requirement":">= 5.2.0 < 6.0.0"}
  ]`
to
`"dependencies": [
    {"name":"puppetlabs/stdlib","version_requirement":">= 5.2.0 < 7.0.0"}
  ]`

Thanks
Kristian

**Comment by ghoneycutt** [comment]
Hi @kmarcroft Could you please send us a pull request? You can edit the file right in your browser.

https://github.com/sgnl05/sgnl05-sssd/edit/master/metadata.json

**Comment by kmarcroft** [comment]
Hi @ghoneycutt,

I have created a PR #110 

Thanks
Kristian
