### ISSUE TITLE
No option to skip package installation

### ISSUE THREAD

**Issue by disconn3ct** [sgnl05/sgnl05-sssd#19]
We use another module that installs the package but does minimal configuration. Since there is no option to skip package installation, we are getting duplicate resource errors. (Using ensure_packages would solve it without major changes.)

**Comment by sgnl05** [comment]
Wouldn't it be sufficient to include sssd::config and sssd::service instead of the main class?

**Comment by disconn3ct** [comment]
Maybe I'm missing something (not the first time by far) but doesn't that make it impossible to override sssd::params without switching over to Hiera?

**Comment by tdevelioglu** [comment]
Better let the sssd::config and sssd:service stay private (preferably even unparameterized) and let only the public interface(s) allow configuring the parameters of the module.

I propose adding a $package_manage flag (default: true) to the main class that can prevent declaring the package resource.

**Comment by dannygoulder** [comment]
#26

**Comment by sgnl05** [comment]
Thanks @dannygoulder !
