### ISSUE TITLE
Service restart issue

### ISSUE THREAD

**Issue by robert4man** [sgnl05/sgnl05-sssd#30]
When upgrading from v0.3.0 -> v0.4.0 I encountered a couple odd issues. It looks like sssd.conf received some extra line spacing to separate the sections (which is fine) resulting in a restart of messagebus, sssd and oddjobd (which also seems fine). Unfortunately it resulted in a couple error conditions for RHEL7:

  1. ssh logins were suddenly very slow, i.e. >25 seconds to connect. Sudo commands were equally slow.
  2. NetworkManager started spewing errors
      - could not create org.freedesktop.DBus proxy
      - GLib-GIO-CRITICAL **: Error while sending AddMatch() message

I was able to resolve both issues with systemctl restart systemd-logind NetworkManager. I was able to reproduce the issue manually with systemctl restart messagebus sssd oddjobd so this may be a system related bug/error. I'm not sure if there is even anything we could do from a puppet module perspective to deal with this condition, but I thought you should be aware.

**Comment by robert4man** [comment]
Now that I look and think about this a little more I'm thinking maybe this construct is a little too basic:
class { '::sssd::config': } ~>
class { '::sssd::service': } ->

sssd.conf changes should only trigger sssd service restarts, not everything.

**Comment by edestecd** [comment]
I can agree with that. The other services were added b/c they were needed by sssd, but they def do not need restarted when config changes happen.

**Comment by sgnl05** [comment]
Fixed in  0.4.1
