### ISSUE TITLE
fails to run if home folder has permission 770

### ISSUE THREAD

**Issue by beetlebolt** [sgnl05/sgnl05-sssd#35]
Error: /Stage[main]/Sssd::Config/Exec[authconfig-mkhomedir]: Could not evaluate: Permission denied @ dir_chdir - /home/peter

It's a known issue when home directories won't let root traverse them (execute privileges).
IOW, if the home directory is 755 the sssd module will successfully run but if a home directory has permissions 754 or 750, the (all) users permission will prevent puppet's root user from accessing the folder.
https://tickets.puppetlabs.com/browse/PUP-5915

**Comment by beetlebolt** [comment]
Good news. This only fails when puppet agent is run via sudo...IOW when a non-root user, who's own home directory has fewer permissions than 755. 
This works:
# /opt/puppetlabs/bin/puppet agent -t
This fails:
$ sudo /opt/puppetlabs/bin/puppet agent -t

**Comment by ghoneycutt** [comment]
Thanks for reporting this. Closing as this is an issue with Puppet itself and not the module.
