### ISSUE TITLE
deprication warnings

### ISSUE THREAD

**Issue by Heidistein** [sgnl05/sgnl05-sssd#36]
As I am cleaning my puppet code, I came across deprecation warnings, emitted by stdlib, originating from sssd. 
/etc/puppetlabs/code/environments/test/modules/sssd/manifests/init.pp line 73 calls 'validate_re', which is depricated: https://github.com/puppetlabs/puppetlabs-stdlib#validate_re

Could be "fixed" using something like:
validate_legacy("Optional[String]", "validate_re", "Value to be validated", ["."])
which would break puppet3 compatibility. 

Low priority, imho.

**Comment by ghoneycutt** [comment]
In issue #37 I asked for a v1.0.0 release. After that, suggest a v2.0.0 that drops support for Puppet v3 and implements data types and related Puppet v4 only features, which will stop these deprecation warnings.

**Comment by edestecd** [comment]
At some point we need to depreciate puppet 3 support.
It was EOL Dec 2016, so any time now.
