### ISSUE TITLE
Cut v1

### ISSUE THREAD

**Issue by ghoneycutt** [sgnl05/sgnl05-sssd#37]
This module has been stable for awhile, could we have a version 1.0.0 release?

**Comment by edestecd** [comment]
http://semver.org/#how-do-i-know-when-to-release-100

**Comment by sgnl05** [comment]
I'm having a rather busy week. :/

Can one of you please update the changelog with recent changes and prepare the v1 release?

**Comment by ghoneycutt** [comment]
Created in PR #38
