### ISSUE TITLE
No service refresh after conf change

### ISSUE THREAD

**Issue by tux-o-matic** [sgnl05/sgnl05-sssd#43]
Why is there no notify or subscribe link between the File resource for sssd.conf and the Service sssd?

**Comment by edestecd** [comment]
That is handled here:
https://github.com/sgnl05/sgnl05-sssd/blob/master/manifests/init.pp#L77

The ~> says to notify and services in the `class { '::sssd::service': }`

**Comment by tux-o-matic** [comment]
I'd say that defines order. Not proper subscription or notify.
Try debugging a config change and there won't be any service refresh triggered.

**Comment by edestecd** [comment]
-> defines just order (require)
~> defines notify/subscribe

https://docs.puppet.com/puppet/5.1/lang_relationships.html#syntax-chaining-arrows

**Comment by tux-o-matic** [comment]
Yes, on resource. Here on classes it's not the same behaviour.
If it were, I'd expect the logs to show a refresh event but it doesn't.

**Comment by edestecd** [comment]
That has been working on classes for quite some time and there are many examples of modules that use this pattern. What version of puppet are you using? Perhaps it is broken or depreciated in some version?

**Comment by tux-o-matic** [comment]
Witnessed that in 4.10. Change to sssd.conf did not lead to a service refresh.

**Comment by tux-o-matic** [comment]
Can we re-open this issue and have this relation changed to really trigger a service refresh,
