### ISSUE TITLE
dbus package not installed

### ISSUE THREAD

**Issue by ytra** [sgnl05/sgnl05-sssd#48]
Target OS: RHEL6

==> wls: Debug: Executing: '/bin/rpm -q sssd --nosignature --nodigest --qf '%{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n''
==> wls: Debug: Executing: '/usr/bin/yum -d 0 -e 0 -y list sssd'
==> wls: Debug: Package[sssd](provider=yum): Ensuring => present
==> wls: Debug: Executing: '/usr/bin/yum -d 0 -e 0 -y install sssd'
==> wls: Notice: /Stage[main]/Sssd::Install/Package[sssd]/ensure: created
==> wls: Debug: /Stage[main]/Sssd::Install/Package[sssd]: The container Class[Sssd::Install] will propagate my refresh event
==> wls: Debug: Class[Sssd::Install]: The container Stage[main] will propagate my refresh event
==> wls: Debug: Executing: '/sbin/service messagebus status'
==> wls: Debug: Executing: '/sbin/chkconfig messagebus'
==> wls: Debug: Executing: '/sbin/service messagebus start'
==> wls: Error: Could not start Service[messagebus]: Execution of '/sbin/service messagebus start' returned 1: messagebus: unrecognized service

The service messagebus becomes available after installation of the dbus package.

**Comment by ghoneycutt** [comment]
@ytra is this still an issue using the latest version of the module?

**Comment by ghoneycutt** [comment]
Please re-open if this is still an issue with our latest version and we'll be happy to help.
