### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ghoneycutt** [sgnl05/sgnl05-sssd#5]
@edestecd @sgnl05 I'm interested in your code but can't use it because there are no licensing terms. Could you add a license? Suggest GPLv3 or Apache v2.

**Comment by edestecd** [comment]
I prefer GPL-3.0+, but I'll let @sgnl05 ultimately decide, since he started the module...

**Comment by ghoneycutt** [comment]
I'm not positive, but I think you both need to specify your licensing since you both contributed work.

**Comment by edestecd** [comment]
Probably,  but if we agree, we can just pick one for the module.

**Comment by sgnl05** [comment]
metadata.json already states that the license is Apache-2.0 (which Puppet suggests as default), but I've forgotten to include the LICENCE file. However I don't really have any preferences when it comes to apache or GPL, so if you @edestecd have strong feelings for GPL, then we'll go for that. :)

**Comment by sgnl05** [comment]
Changed licence to GPL-3.0+ in metadata.json and added a LICENCE file. This should cover it for both of us, right @edestecd ?

**Comment by edestecd** [comment]
Looks good to me.
