### ISSUE TITLE
Module does not work on OracleLinux

### ISSUE THREAD

**Issue by tomnowak** [sgnl05/sgnl05-sssd#50]
I get the following error when running on OracleLinux:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, operatingsystem is <OracleLinux> which is not supported at /etc/puppetlabs/code/environments/production/modules/sssd/manifests/params.pp:43:11

as the params.pp have missing OracleLinux part:

$ diff params.pp.orig params.pp
45c45
<         'RedHat', 'CentOS': {
---
>         'RedHat', 'CentOS', 'OracleLinux': {

Regards,
Tomasz

**Comment by ghoneycutt** [comment]
The case statement for EL should be redone to not use $operatingsystem.

```puppet
case $osfamily {
  case $::operatingsystemmajrelease {
    '5','6','7': {
      # set values for EL 5 - 7
    }
    '25','26': {
      # set values for Fedora 25 and 26
    }
  }
}
```

**Comment by sgnl05** [comment]
Will be fixed in next release. Thanks @ghoneycutt !
