### ISSUE TITLE
v2.1.0 killed support for CloudLinux

### ISSUE THREAD

**Issue by dreadmin** [sgnl05/sgnl05-sssd#53]
https://github.com/sgnl05/sgnl05-sssd/blob/bdb0d967c41761e3f202f4026090ae76f134ffcb/manifests/params.pp#L45

CloudLinux for all intents and purposes can be treated the same as CentOS for this module. Any chance of getting it added into that case statement alongside CentOS?

**Comment by sgnl05** [comment]
Sure :) Should be fixed with #51.
