### ISSUE TITLE
v0.3.0 & 2.1.0: [RHEL 7.3] fails on create config file

### ISSUE THREAD

**Issue by KoffieNu** [sgnl05/sgnl05-sssd#54]
When module is used on a system without sssd installed, it tries to create config before installing sssd (and failing, as /etc/sssd dir is absent)

Error: /Stage[main]/Sssd::Config/File[sssd.conf]/ensure: change from absent to present failed: Could not set 'present' on ensure: No such file or directory @ dir_s_mkdir

Work-around: create dir /etc/sssd or ensure it's existance in another, earlier used, module.
Fix would be not to create config when package isn't installed or create dir as well.

(tested on 0.3.0 and 2.1.0 version of module)

**Comment by ghoneycutt** [comment]
@KoffieNu is this still the case using the latest (2.2.1) version of this module?

**Comment by ghoneycutt** [comment]
In our current version the package comes before the sssd.conf file, so this should no longer be an issue. Please re-open if it is and we'll be happy to help!
