### ISSUE TITLE
2.2.0 version no longer works on Ubuntu

### ISSUE THREAD

**Issue by tomnowak** [sgnl05/sgnl05-sssd#57]
Hi,
The latest version 2.2.0 works again on Oracle Linux :) but is broken on Ubuntu now:(

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, osfamily Debian's os.release.major is <14.04> and must be 7 or 8 for Debian and 14 or 16 for Ubuntu.

**Comment by ghoneycutt** [comment]
Thanks for letting us know! Could you please post the output of `facter`.

**Comment by tomnowak** [comment]
Ubuntu 14.04
# facter facterversion os ruby
facterversion => 3.6.7
os => {
  architecture => "amd64",
  distro => {
    codename => "trusty",
    description => "Ubuntu 14.04.5 LTS",
    id => "Ubuntu",
    release => {
      full => "14.04",
      major => "14.04"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Ubuntu",
  release => {
    full => "14.04",
    major => "14.04"
  },
  selinux => {
    enabled => false
  }
}
ruby => {
  platform => "x86_64-linux",
  sitedir => "/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.1.0",
  version => "2.1.9"
}

Ubuntu 16.04
facterversion => 3.6.7
os => {
  architecture => "amd64",
  distro => {
    codename => "xenial",
    description => "Ubuntu 16.04.3 LTS",
    id => "Ubuntu",
    release => {
      full => "16.04",
      major => "16.04"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Ubuntu",
  release => {
    full => "16.04",
    major => "16.04"
  },
  selinux => {
    enabled => false
  }
}
ruby => {
  platform => "x86_64-linux",
  sitedir => "/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.1.0",
  version => "2.1.9"
}

**Comment by ghoneycutt** [comment]
I think that's a bug in facter. It is showing os.family.major as 14.04 instead of 14. I'll dig into this more.

**Comment by ghoneycutt** [comment]
@tomnowak Could you try facter v3.9.3 and see if os.family.major still returns 14.04 ?

**Comment by ghoneycutt** [comment]
Created https://tickets.puppetlabs.com/browse/FACT-1794

**Comment by tomnowak** [comment]
I think that always was like this on Ubuntu:

https://puppet.com/docs/facter/3.9/core_facts.html#operatingsystemmajrelease
Caveats:
    Linux: for Ubuntu, the major release is X.Y (e.g. “10.4”).

**Comment by ghoneycutt** [comment]
Ugh, that sucks. So if you run 16.10 instead of using the same data as 16.04, it would fail.

**Comment by ghoneycutt** [comment]
@tomnowak could you post the full output of facter, minus any identifiable info like IP and MAC.

**Comment by tomnowak** [comment]
Attached are outputs of facter from native and aio puppet versions on Ubuntu 16.04

[xenial-aio-facter_3.6.8.txt](https://github.com/sgnl05/sgnl05-sssd/files/1457427/xenial-aio-facter_3.6.8.txt)
[xenial-native-facter_2.4.6.txt](https://github.com/sgnl05/sgnl05-sssd/files/1457428/xenial-native-facter_2.4.6.txt)

**Comment by ghoneycutt** [comment]
Fix released in 2.2.1
