### ISSUE TITLE
data_provider hiera in metadata.json deprecated in puppet >= 4

### ISSUE THREAD

**Issue by ytra** [sgnl05/sgnl05-sssd#58]
Warning: Defining "data_provider": "hiera" in metadata.json is deprecated. It is ignored since a 'hiera.yaml' with version >= 5 is present
(in /etc/puppetlabs/code/environments/production/modules/sssd/metadata.json)

Removal of the data_provider on line 16 of metadata.json is the only thing that needs to be done

**Comment by ghoneycutt** [comment]
Thank you! Where do you see this warning?

**Comment by mUbsta** [comment]
As per the error this warning occurs when hiera.yaml is set to 5 (or above).

See [https://puppet.com/docs/puppet/5.3/modules_metadata.html#deprecated-keys](url)

**Comment by ghoneycutt** [comment]
Thanks @mUbsta 

Submitting a fix for this in PR #61

**Comment by ghoneycutt** [comment]
Released in 2.2.2
