### ISSUE TITLE
2.2.1 no longer works on Debian 9

### ISSUE THREAD

**Issue by tomnowak** [sgnl05/sgnl05-sssd#60]
Hi,
  The latest version 2.2.1 got fixed on Ubuntu 14.04 and 16.04, but not longer works on my Debian 9 machines:(

  I think for Debian family OSes it will be easier just ignore the OS release, as I think sssd is part of all currently supported Debian and Ubuntu releases.

Regards,
Tomasz

**Comment by ghoneycutt** [comment]
We don't support Debian 9 yet, though would certainly like to.

If you add `'9'` to the array at the end of this line https://github.com/sgnl05/sgnl05-sssd/blob/master/manifests/init.pp#L101 does it work as expected?

**Comment by tomnowak** [comment]
I can confirm that adding '9' to the array of supported Debian releases fixes the issue.

**Comment by ghoneycutt** [comment]
Created PR #62 to add Debian 9 support

**Comment by ghoneycutt** [comment]
Released in 2.3.0
