### ISSUE TITLE
Package sssd-32bit is not available on 32 bit Suse

### ISSUE THREAD

**Issue by mxey** [sgnl05/sgnl05-sssd#82]
The module always tries to install the package `sssd-32bit` on Suse systems. But the package only exists on 64-bit systems, not on 32-bit systems. Leads to this error:

`change from absent to present failed: Execution of '/usr/bin/zypper --quiet install --auto-agree-with-licenses --no-confirm --name sssd-32bit' returned 104: Package 'sssd-32bit' not found`

**Comment by ghoneycutt** [comment]
what fact from facter can be used to differentiate 32bit systems?

**Comment by mxey** [comment]
> what fact from facter can be used to differentiate 32bit systems?

`os.architecture`

**Comment by ghoneycutt** [comment]
What's the value?

**Comment by ghoneycutt** [comment]
Which version(s) of Suse are you using this on?

**Comment by mxey** [comment]
> What's the value?
i386 in the case of SLES

> Which version(s) of Suse are you using this on?
SLES 11

**Comment by ghoneycutt** [comment]
Do you have the ability to test SLES 12?

**Comment by mxey** [comment]
> Do you have the ability to test SLES 12?

Yes. Let me test your patch and get back to you.
