### ISSUE TITLE
Support for Fedora 29

### ISSUE THREAD

**Issue by mungo312** [sgnl05/sgnl05-sssd#90]
Hi,
the module currently does not support Fedora 28 and 29. Since Fedora 28 authconfig is deprecated and authselect is used. 
I can provide some of the support but my knowledge of spec tests is zero.

**Comment by ghoneycutt** [comment]
I can help you with the spec tests if you can submit a PR.

**Comment by ghoneycutt** [comment]
Closing due to lack of response.
