### ISSUE TITLE
Version check in init.pp is incorrect

### ISSUE THREAD

**Issue by hawkeye-7** [sgnl05/sgnl05-sssd#94]
Line 95 of init.pp is in error. It says "Amazon" when it should say "RedHat" .

As a consequence, Amazon would never work, and  RedHat allows version 5 through when it should not. 

It would be nice though if the product worked with RedHat 8 as well.

**Comment by sgnl05** [comment]
It's just to trigger a warning that you are using an unsupported platform. Warnings do not stop a puppet run. See https://puppet.com/docs/puppet/latest/function.html#warning for more details.

RedHat 8 support has been added today and will be uploaded to Puppet Forge later today
